@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM1OTc1NjZ9.pZgzee_7SZjUy0mMnYyET30ocI9U5d77zmwfmNABO1M

###

GET http://localhost:3000/movies
Authorization: Bearer {{ jwt }}

### SEE MOVIES

GET http://localhost:3000/movies/30

### CREATE

POST http://localhost:3000/movies
Content-Type: application/json

{
  "english": true
}

### UPDATE

PATCH http://localhost:3000/movies/11
Content-Type: application/json

{
  "english": true
}

### DELETE

DELETE http://localhost:3000/movies/3




### ACTORS BELOW

GET http://localhost:3000/actors

###

GET http://localhost:3000/actors/18

###

POST http://localhost:3000/actors
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "first_name": "Yellow",
  "last_name": "Brick Road",
  "known_for": "ayooooooooo",
  "age": 50,
  "movie_id": 14
}

###

PATCH http://localhost:3000/actors/34
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "gender": "male"
}

###

DELETE http://localhost:3000/actors/29


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Lechuga",
  "email": "lechuga@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "bear@test.com",
  "password": "password"
}

### Movie_Genres create
POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "movie_id": 16,
  "genre_id": 1
}