GET http://localhost:3000/movies

### SEE MOVIES

GET http://localhost:3000/movies/30

### CREATE

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "B",
  "year": 1558,
  "plot": "I am batmannnnnnnnnn"
}

### UPDATE

PATCH http://localhost:3000/movies/30
Content-Type: application/json

{
  "year": 1800
}

### DELETE

DELETE http://localhost:3000/movies/3




### ACTORS BELOW

GET http://localhost:3000/actors

###

GET http://localhost:3000/actors/30

###

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "R",
  "last_name": "Rover",
  "known_for": "Send em over!",
  "age": 13
}

###

PATCH http://localhost:3000/actors/38
Content-Type: application/json

{
  "first_name": "Tara",
  "last_name": "Y"
}

###

DELETE http://localhost:3000/actors/29