# Actor.create!([
#   {first_name: "Big", last_name: "Bad", known_for: "Wolf", gender: "F", age: 29},
#   {first_name: "Lamonica", last_name: "Willms", known_for: "Return of the Man", gender: "F", age: 98},
#   {first_name: "Carla", last_name: "Ferry", known_for: "Forbidden Hills", gender: "F", age: 45},
#   {first_name: "Edythe", last_name: "Flatley", known_for: "Journey of the Mutant", gender: "M", age: 35},
#   {first_name: "Salina", last_name: "Blanda", known_for: "The Red Blow from Mars", gender: "F", age: 64},
#   {first_name: "Nam", last_name: "Botsford", known_for: "Dangerous Cousins", gender: "F", age: 32},
#   {first_name: "Olga", last_name: "Conroy", known_for: "The Cousins from Outer Space", gender: "F", age: 25},
#   {first_name: "Mari", last_name: "Herzog", known_for: "Action Jungle", gender: "M", age: 19},
#   {first_name: "Geoffrey", last_name: "Labadie", known_for: "The Green Cat from Across the Ocean", gender: "M", age: 57},
#   {first_name: "Janey", last_name: "Bartell", known_for: "The Wolf from Across the Ocean", gender: "M", age: 34},
#   {first_name: "Lanie", last_name: "Cremin", known_for: "Red Ninjas", gender: "M", age: 45},
#   {first_name: "Henriette", last_name: "Kertzmann", known_for: "Blonde Fly", gender: "M", age: 58},
#   {first_name: "Caprice", last_name: "Tremblay", known_for: "Bloody Brains 2: Son of Bloody Brains", gender: "M", age: 80},
#   {first_name: "Jill", last_name: "Quitzon", known_for: "The Tentacle from Jupiter South/Abacoa", gender: "F", age: 25},
#   {first_name: "Monserrate", last_name: "Rogahn", known_for: "Dangerous Witch", gender: "F", age: 31},
#   {first_name: "Abby", last_name: "Bailey", known_for: "Hard Boiled Ninjas", gender: "F", age: 18},
#   {first_name: "Jung", last_name: "Crist", known_for: "921 A.D.", gender: "F", age: 50},
#   {first_name: "Melissa", last_name: "Nader", known_for: "Action Pickpocket", gender: "F", age: 40},
#   {first_name: "Scarlet", last_name: "Murphy", known_for: "Nuclear Brains", gender: "F", age: 30},
#   {first_name: "Vida", last_name: "DuBuque", known_for: "Action City", gender: "F", age: 20},
#   {first_name: "Ingrid", last_name: "Block", known_for: "Legend of American Friday", gender: "F", age: 60},
#   {first_name: "Earline", last_name: "Lubowitz", known_for: "Nuclear Ninja", gender: "M", age: 70},
#   {first_name: "Serena", last_name: "Parker", known_for: "The Friday from 18988 Leagues", gender: "F", age: 80},
#   {first_name: "Weston", last_name: "Quitzon", known_for: "The Mutant from Hell", gender: "F", age: 89},
#   {first_name: "Tangela", last_name: "Ledner", known_for: "The American Friday from Hell", gender: "F", age: 79},
#   {first_name: "Ambrose", last_name: "Wolff", known_for: "Death Clash", gender: "F", age: 69},
#   {first_name: "Sharyn", last_name: "Von", known_for: "Hard Boiled Imp", gender: "F", age: 59},
#   {first_name: "Pamella", last_name: "Hudson", known_for: "Hard Boiled Men", gender: "M", age: 49},
#   {first_name: "Penny", last_name: "Senger", known_for: "Rise of the Clash", gender: "F", age: 39},
#   {first_name: "Wilbur", last_name: "Volkman", known_for: "Hungry Clash", gender: "M", age: 29},
#   {first_name: "Josie", last_name: "Blanda", known_for: "The Dangerous Identity with a Thousand Faces", gender: "F", age: 19},
#   {first_name: "Red", last_name: "Rover", known_for: "Send em over!", gender: "F", age: 36},
#   {first_name: "Tara", last_name: "Rover", known_for: "Send em over!", gender: "F", age: 24}
# ])
# Movie.create!([
#   {title: "Yellow Snow", year: 1998, plot: "Dogs... everywhere... holy moly", director: "Pentatonix", english: nil},
#   {title: "The blood orange sun", year: 2020, plot: "it will destroy us all. Drink water or regret living", director: "Pentatonix", english: nil},
#   {title: "I Married a Tentacle", year: 2015, plot: "The whiter and fresher the cheese, the crisper and fruitier the wine should be taste and texture in all colours say cheese raw milk is unpasteurized in an artisan farmerhouse soft ripening cheese for but round cheeses are to be cut in wedges, like a cake so cute but cheesy bergkäse from the Alps blend the flour, cheese and.", director: "Pentatonix", english: nil},
#   {title: "Green Rain: The Tamiko Schmidt Story", year: 1970, plot: "Salt, pepper, mustard and vinegar blue fungi in cream when the rennet is added, curds are formed applewood smoked in an artisan farmerhouse applewood smoked is like chalk and cheese but don't you agree? It is no use crying over spilled milk until the wheels form a white coat of penicillium moulds the slice of cheese is placed on top of the meat patty.", director: "Pentatonix", english: nil},
#   {title: "The Man from 12023 Leagues", year: 1927, plot: "With dutch courage washed curd cheese is like chalk and cheese blue fungi in cream double dutch or dutch sandwich - tongue in cheek trying too hard, unsubtle, and inauthentic trying too hard, unsubtle, and inauthentic soft ripening cheese for.", director: "Pentatonix", english: nil},
#   {title: "Women 2: Electric Boogaloo", year: 1971, plot: "The slice of cheese is placed on top of the meat patty New York cheesecake blue fungi in cream when the rennet is added, curds are formed harmful secondary metabolites Penicillium roqueforti they were so cheesed off cheese paring with wine but poets have been mysteriously silent on the subject of cheese double dutch or.", director: "Pentatonix", english: nil},
#   {title: "The Wolves from Across the Ocean", year: 1920, plot: "In an artisan farmerhouse double dutch or bergkäse from the Alps he old cheese dairy buildings, situated on the historic site washed curd cheese New York cheesecake but don't you agree? It is no use crying over spilled milk washed curd cheese - tongue in cheek dutch sandwich.", director: "Pentatonix", english: nil},
#   {title: "War of the Man", year: 1961, plot: "Salt, pepper, mustard and vinegar dutch sandwich applewood smoked cheeseparing it is blue sky thinking the moon is made of green cheese and dutch sandwich - tongue in cheek so cute but cheesy of cheesy business lingo.", director: "MEEEE", english: nil},
#   {title: "The Men", year: 1928, plot: "Sheridans cheesemongers the whiter and fresher the cheese, the crisper and fruitier the wine should be the slice of cheese is placed on top of the meat patty washed curd cheese so cute but cheesy raw milk is unpasteurized is like chalk and cheese and wrap blue cheeses all over as mould spores spread readily he old cheese dairy buildings, situated on the historic site it is blue sky thinking.", director: "Pentatonix", english: nil},
#   {title: "The World from Across the Ocean", year: 1963, plot: "Team cheesy says hi the milky way of of cheesy business lingo and wrap blue cheeses all over as mould spores spread readily New York cheesecake the milky way of it is blue sky thinking the early bird may get the worm, but the second mouse gets the cheese in the trap but don't you agree? It is no use crying over spilled milk What do you call cheese that isn't yours? Nacho Cheese;.", director: "Snarky Puppy", english: nil},
#   {title: "I Married a Death Friday", year: 1914, plot: "Of cheesy business lingo 10 grilled cheese sandwiches you should try immediately with he old cheese dairy buildings, situated on the historic site What do you call cheese that isn't yours? Nacho Cheese; raw milk is unpasteurized What do you call cheese that isn't yours? Nacho Cheese; it is blue sky thinking the milky way of of the Friesian herd the early bird may get the worm, but the second mouse gets the cheese in the trap.", director: "Snarky Puppy", english: nil},
#   {title: "Dangerous Woman", year: 1939, plot: "Of cheesy business lingo with Dutch courage cheese paring with wine New York cheesecake cheeseparing New York cheesecake Penicillium roqueforti it is blue sky thinking is like chalk and cheese so cute but cheesy.", director: "Snarky Puppy", english: nil},
#   {title: "The Red Wolves from the Black Lagoon", year: 1920, plot: "Penicillium roqueforti they were so cheesed off and wrap blue cheeses all over as mould spores spread readily the sticky nature of processed cheese can make it difficult to slice, but cheese paring with wine say cheese - tongue in cheek of cheesy business lingo salt, pepper, mustard and vinegar What do you call cheese that isn't yours? Nacho Cheese;.", director: "Snarky Puppy", english: nil},
#   {title: "I am Monster", year: 1926, plot: "But don't you agree? it is no use crying over spilled milk processed cheese has several technical advantages over traditional cheese coagulation of the milk protein casein they can also age quite well in ripening cellars where taste and texture in all colours cheese paring with wine the moon is made of green cheese and and wrap blue cheeses all over as mould spores spread readily cut the cheese the milky way of.", director: "Snarky Puppy", english: nil},
#   {title: "Action Ninja 2: Son of Action Ninja", year: 1907, plot: "In an artisan farmerhouse Penicillium roqueforti but round cheeses are to be cut in wedges, like a cake bergkäse from the Alps the milky way of in an artisan farmerhouse cheese paring with wine they can also age quite well in ripening cellars where the milky way of harmful secondary metabolites.", director: "Snarky Puppy", english: nil},
#   {title: "Death Wolves", year: 1997, plot: "Of cheesy business lingo the milky way of 10 grilled cheese sandwiches you should try immediately with blessed are the cheesemakers harmful secondary metabolites they were so cheesed off cheeseparing applewood smoked but round cheeses are to be cut in wedges, like a cake they were so cheesed off.", director: "Snarky Puppy", english: nil},
#   {title: "Green Wizard", year: 1991, plot: "Soft ripening cheese for of the Friesian herd soft ripening cheese for What do you call cheese that isn't yours? Nacho Cheese; New York cheesecake cut the cheese the moon is made of green cheese and the early bird may get the worm, but the second mouse gets the cheese in the trap but poets have been mysteriously silent on the subject of cheese but round cheeses are to be cut in wedges, like a cake.", director: "Snarky Puppy", english: nil},
#   {title: "The Ultra Diaries from Hell", year: 2010, plot: "He old cheese dairy buildings, situated on the historic site they can also age quite well in ripening cellars where dutch sandwich in an artisan farmerhouse wash, rinse, repeat he old cheese dairy buildings, situated on the historic site but round cheeses are to be cut in wedges, like a cake cut to size double dutch or Sheridans Cheesemongers.", director: "Snarky Puppy", english: nil}
# ])